name: Deploy

on:
  push:
    branches:
      - '*'  # Trigger on any branch push

concurrency:
  group: shared-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deploy Message
        run: echo "Deploying on branch ${{ github.ref_name }}"
      - name: Sleep to simulate long deploy
        run: sleep 60
